kind: Pod
apiVersion: v1
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  containers:
  - name: mongo
    image: mongo:3.6
    volumeMounts:
      - mountPath: /data/db
        name: data
  volumes:
    - name:  data
      emptyDir: {}