kind: Pod
apiVersion: v1
metadata:
  name: alpine
  labels:
    name: alpine
spec:
  containers:
  - name: alpine
    image: alpine
    command:
      - "sleep"
      - "10000"
    volumeMounts:
      - name:  creds
        mountPath:  "/etc/creds"
  volumes:
    - name:  creds
      secret:
        secretName: mongo-creds
        items:
        - key: username.txt
          path: service
        - key: password.txt
          path: service
