kind: Pod
apiVersion: v1
metadata:
  name: alpine
  labels:
    name: alpine
spec:
  containers:
  - name: alpine
    image: alpine
    command:
      - 'sleep'
      - '1000'
    env:
      - name:  MONGO_URL
        valueFrom:
          secretKeyRef:
            name:  mongo-creds
            key:  mongoURL