kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: www-domain
spec:
  rules:
  - host: example.com
    http:
      paths:
        - backend:
            serviceName: ahmed
            servicePort: 80
